version: '3.0'
services:

  api:
    build: ./server/
    container_name: api
    ports:
      - "9000:9000"
    command: npm start
    environment:
      MONGO_URI: mongodb://sniper:1212@db:27017
    volumes:
      - "./server/:/app"
      - "/app/node_modules"
    # networks:
    #   - pos_network

  web:
    build: ./client/
    container_name: web
    ports:
      - "3291:3291"
    command: npm start
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    environment:
      MONGO_URI: mongodb://root:1212@db:27017/pos
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1212
    volumes:
      - pos_db_volume:/data/db

volumes:
  pos_db_volume:


